[[redirects]]
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/:splat"

[build]
  functions = "functions"

[dev]
  framework = "vue"

[functions]
  external_node_modules = ["chrome-aws-lambda"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"